### PR TITLE
Write-up for the motivation and purpose session

### PR DESCRIPTION
**Pull request by jackyho112**
I welcome any feedback!

### CODE REVIEW

**Review by merveshin — COMMENTED** [review]
it looks ok but maybe a little bit long for the motivation part we may add 4th part to the usage scenario

**Review by bbaillie — COMMENTED** [review]
lots of typos to be fixed and some sentences need to be restructured but the overall content is right on the mark for what we want

**Comment by jackyho112** [comment]
@bbaillie, @merveshin made lots of improvements. The word count is 260, so I would say it's reasonable. If you guys are ok with it, feel free to merge it!

**Review by bbaillie — COMMENTED** [review]
New changes look awesome!

**Pull request merged**
